// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quan_Ly_Khach_san.DATA;

#nullable disable

namespace Quan_Ly_Khach_san.Migrations
{
    [DbContext(typeof(QLBHDbContext))]
    partial class QLBHDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.DatPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDatPhong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("PhongID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("PhongID");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.DichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.LoaiPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuyenHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.Phong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DichvuID")
                        .HasColumnType("int");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("LoaiPhongID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiPhong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DichvuID");

                    b.HasIndex("LoaiPhongID");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.DatPhong", b =>
                {
                    b.HasOne("Quan_Ly_Khach_san.DATA.KhachHang", "KhachHang")
                        .WithMany("DatPhong")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Khach_san.DATA.NhanVien", "NhanVien")
                        .WithMany("DatPhong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Khach_san.DATA.Phong", "Phong")
                        .WithMany("DatPhong")
                        .HasForeignKey("PhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.Phong", b =>
                {
                    b.HasOne("Quan_Ly_Khach_san.DATA.DichVu", "Dichvu")
                        .WithMany()
                        .HasForeignKey("DichvuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Khach_san.DATA.LoaiPhong", "LoaiPhong")
                        .WithMany("Phong")
                        .HasForeignKey("LoaiPhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dichvu");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.KhachHang", b =>
                {
                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.LoaiPhong", b =>
                {
                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.NhanVien", b =>
                {
                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("Quan_Ly_Khach_san.DATA.Phong", b =>
                {
                    b.Navigation("DatPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
